SELECT 
  EMPNO, 
  LEVEL AS LV,
  ENAME, 
  MGR,
  PRIOR ENAME AS MGR_ENAME,
  SUBSTR(SYS_CONNECT_BY_PATH(ENAME, '-'), 2) AS ENAMES
FROM 
  EMP A
START WITH
  MGR IS NULL
CONNECT BY PRIOR
  EMPNO = MGR
;